### ISSUE TITLE
ngrok error

### ISSUE THREAD

**Issue by weex** [j-chimienti/pollofeed#3]
The site is showing an error now. 
![Screen Shot 2019-06-24 at 2 34 13 PM](https://user-images.githubusercontent.com/38776/60053611-2bbef200-968d-11e9-9d9d-96aad170b44d.png)

**Comment by j-chimienti** [comment]
Thanks dude I saw this email during dinner and started freaking.

Seems to have been a typo w/ motion.service file. Should be good now
